# Basic set up for three package managers

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  # Workflow files stored in the
  # default location of `.github/workflows`
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: aws-*

