  name: Pull Request
  on:
    pull_request:
      branches:
        - main
      types: [opened, synchronize, reopened, closed, labeled, unlabeled]

  jobs:
    context:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - id: affected
          uses: cloudposse/github-action-atmos-affected-stacks@v0.0.1

      outputs:
        affected: ${{ steps.affected.outputs.affected }}
        matrix: ${{ steps.affected.outputs.matrix }}