name: Actions Workflow
on: 
  push:
    branches:
      - dev

jobs:
  deploy:
    name: STS get caller identity. Test aws-actions/configure-aws-credentials
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Copy files to the test website with the AWS CLI
      run: |
        aws sts get-caller-identity
    
    - name: Get secrets by name and by ARN
      uses: aws-actions/aws-secretsmanager-get-secrets@v1
      with:
        secret-ids: |
          SECRET_ALIAS_1,test/secret
          SECRET_ALIAS_2,arn:aws:secretsmanager:eu-east-1:068456885903:secret:test2-a1b2c3
    