name: update docker actions

on:
  push:
    
    branches:
      - foo
    
jobs:
  update_aws_actions:
     runs-on: ubuntu-latest

     steps:
       - uses: docker/login-action@v1
       - uses: docker/build-push-action@v2
       - uses: docker/setup-buildx-action@v1