name: Interact with github API

on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
# Reference https://docs.github.com/en/actions/security-guides/automatic-token-authentication
  create_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write 
      pull-requests: write
    steps:
      - name: Create issue using REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit: ${{ github.sha }}",
            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
            }' \
          --fail
      - name: Create a PR 
        run: |
          echo GITHUB_REPOSITORY: ${{ github.repository }}
          echo GITHUB_ACTOR: ${{ github.action }}
          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{github.actor}}/${{ github.repository }}/pulls \
          -d '{"title":"Amazing new feature","body":"Please pull these awesome changes in!","head":"octocat:new-feature","base":"master"}'
            
