name: Interact with github API

on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
# Reference https://docs.github.com/en/actions/security-guides/automatic-token-authentication
  step-0:
    
      
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
     

    steps:  
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Let's get all the branches

      - name: Prepare a branch
        run: |
          echo "Make sure we are on step 0"
          if [ "$(cat .github/script/STEP)" != 0 ]
          then
            echo "Current step is not 0"
            exit 0
          fi

          echo "Make a branch"
          BRANCH=update-game
          git checkout -b $BRANCH

          echo "Update index.html"
          sed -i.bak 's/Game over/Game over, refresh to play again 🧑‍💻 🤖!/' index.html

          echo "Make a commit"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add index.html
          git commit --message="Update game over message"

          echo "Push"
          git push --set-upstream origin $BRANCH

          
          echo "Restore main"
          git checkout main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        

      - name: Create a PR 
        env:
          BRANCH: update-game
        run: |

          sed -i.bak 's/GITHUB_ACTOR/${{github.actor }}/' .github/script/data.json
          cd .github/script

          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/pulls \
          -d @data.json
            
