name: "Setup jq Example - Linux"

on:
  push:
    branches:
      - dev
    # inputs:
    #   version:
    #     type: string
    #     required: false
    #     description: "Version of jq to install"
    #     default: "1.6"
    #   force:
    #     type: boolean
    #     required: false
    #     description: "Do not check for existing jq installation before continuing."
    #     default: false

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      # - name: 'Setup jq'
      #   uses: dcarbone/install-jq-action@v1.0.1
      #   with:
      #     version: '${{ inputs.version }}'
      #     force: '${{ inputs.force }}'

      # - name: 'Check jq'
      #   run: |
      #     which jq
      #     jq --version
      - uses: dsaltares/fetch-gh-release-asset@1.1.0
        with:
          repo: 'dsaltares/godot-wild-jam-18'
          version: 'tags/v0.1.18'
          file: 'plague-linux.zip'
          token: ${{ secrets.GITHUB_TOKEN }}