name: Matrix
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  
  node-version:
    runs-on: ubuntu-lastest
    steps: 
      - name: Log node version
        run: node -v
      
      - name: update node version
        uses: actions/setup-node@v1
        with:
          node-version: 6
      - name: Log node version
        run: |
          node -v
        
