name: "Close stale issues"

# Controls when the action will run.
on:
  push:
    branches:
      - master

jobs:
  cleanup:
    runs-on: ubuntu-latest
    name: Stale issue job
    steps:
    - uses: aws-actions/stale-issue-cleanup@v6
      with:
        # Setting messages to an empty string will cause the automation to skip
        # that category
        ancient-issue-message: Ancient issue message
        ancient-pr-message: Ancient pr message
        stale-issue-message: Stale issue message
        stale-pr-message: Stale issue message

        # These labels are required
        stale-issue-label: closing-soon
        exempt-issue-labels: awaiting-approval
        stale-pr-label: no-pr-activity
        exempt-pr-labels: awaiting-approval
        response-requested-label: response-requested

        # Don't set this to not apply a label when closing issues
        closed-for-staleness-label: closed-for-staleness

        # Issue timing
        days-before-stale: 14
        days-before-close: 7
        days-before-ancient: 365

        # If you don't want to mark a issue as being ancient based on a
        # threshold of "upvotes", you can set this here. An "upvote" is
        # the total number of +1, heart, hooray, and rocket reactions
        # on an issue.
        minimum-upvotes-to-exempt: 1

        repo-token: ${{ secrets.GITHUB_TOKEN }}
        #loglevel: DEBUG
        # Set dry-run to true to not perform label or close actions.
        #dry-run: true