name: Actions Workflow
on: 
  push:
  pull_request:
    types: 
      - closed
      - assigned
      - opened
      - reopened

jobs:
  matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Log node version
        run: node -v  
      - name: update node version
        uses: actions/setup-node@v1
        with:
          node-version: 6
      - name: Log node version
        run: |
          node -v
          
  run-github-actions: 
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
      - name: List files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo $GITHUB_JOB

      - name: Simple JS action
        id: greet
        uses: actions/hello-world-javascript-action@e76147da8e5c81eaf017dede5645551d4b94427b
        with:
          who-to-greet: Manuel
      - name: Log greeting time
        run: echo "${{ steps.greet.outputs.time }}"
      
