name: test dependabot dependency version updates

on:
    push:
        branches:
            
            - releases/*
            - feature/*
jobs:
          
  simple:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
   
    
      
