name: Actions Workflow
on: 
  push: foo-bar
  pull_request:
    types: 
      - closed
      - assigned
      - opened
      - reopened

jobs:
  matrix:
    strategy:
      matrix:
         os: [windows-latest, ubuntu-latest]
         node_version: [6,8,10,12,14,16]
         exclude:
           - os: windows-latest
             node_version: 10
           - os: windows-latest
             node_version: 14
           - os: ubuntu-latest
             node_version: 16
    runs-on: ${{ matrix.os }}
    steps:
      - name: Log node version
        run: node -v  
      - name: update node version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Log node version
        run: |
          node -v
          
  run-github-actions: 
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
      - name: List files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo $GITHUB_JOB

      - name: Simple JS action
        id: greet
        uses: actions/hello-world-javascript-action@e76147da8e5c81eaf017dede5645551d4b94427b
        with:
          who-to-greet: Manuel
      - name: Log greeting time
        run: echo "${{ steps.greet.outputs.time }}"
      
