name: Dependabot auto-label
on: 
  pull_request:
     types:
       - opened
       - labeled
     branches:
       - main

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    # if: ${{ github.actor == 'dependabot[bot]' }}
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    
    steps:       
      - name: Dependabot metadata        
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: set env variables
        run: |
            echo "ACTION_NAMES=${{ steps.metadata.outputs.dependency-names }}" >> $GITHUB_ENV
            echo "PREVIOUS_VERSION=${{ steps.metadata.outputs.previous-version }}" >> $GITHUB_ENV
            echo "NEW_VERSION=${{ steps.metadata.outputs.new-version }}" >> $GITHUB_ENV
            
      
      - uses: actions/checkout@v3
      - name: check envs
        run: |
           echo "GITHUB_ENV: $GITHUB_ENV"
           echo "ACTION_NAMES: ${{env.ACTION_NAMES}}"
           echo "NEW_VERSION: $NEW_VERSION"
      - name: run update_action.py 
        run: |
          python src/update-action.py
       