name: Dependabot auto-label
on: 
  pull_request:
     types:
       - opened
       - labeled
     branches:
       - main

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    # if: ${{ github.actor == 'dependabot[bot]' }}
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    
    steps:       
      - name: Dependabot metadata        
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: set env variables
        run: |
            echo "ACTION_NAMES=${{ steps.metadata.outputs.dependency-names }}" >> $GITHUB_ENV
            echo "PREVIOUS_VERSION=${{ steps.metadata.outputs.previous-version }}" >> $GITHUB_ENV
            echo "NEW_VERION=${{ steps.metadata.outputs.new-version }}" >> $GITHUB_ENV
          
      - name: run update_action.py 
        run: |
          python src/update_actions_json.py
       